name: Scheduled workflow test

on:
  schedule:
    - cron: '*/5 * * * *'
  
  workflow_dispatch:

jobs:
  display:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Display github event
        run: cat $GITHUB_EVENT_PATH
