name: Scheduled workflow test

on:
  schedule:
    - cron: "0 12 1 * *"
  
  workflow_dispatch:

jobs:
  display:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Display github event data
        run: |
          cat $GITHUB_EVENT_PATH
          echo $GITHUB_SHA
          echo $GITHUB_ACTOR
          echo $GITHUB_REF
